/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.correo;

/**
 *
 * @author piero
 */
public class LoginCorreo extends javax.swing.JFrame {
  int xMouse, yMouse;
  /**
   
   */
  public LoginCorreo() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Fondo = new javax.swing.JPanel();
    LogoEmpresa = new javax.swing.JLabel();
    Header = new javax.swing.JPanel();
    ExitBtn = new javax.swing.JPanel();
    Exit = new javax.swing.JLabel();
    NameInterfaz = new javax.swing.JLabel();
    IconInterfaz = new javax.swing.JLabel();
    InfoCorreo = new javax.swing.JLabel();
    correoTxt = new javax.swing.JTextField();
    InfoContra = new javax.swing.JLabel();
    contraTxt = new javax.swing.JTextField();
    LoginBtn = new javax.swing.JPanel();
    LoginInfo = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    jSeparator2 = new javax.swing.JSeparator();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setLocationByPlatform(true);
    setUndecorated(true);
    setResizable(false);

    Fondo.setBackground(new java.awt.Color(255, 255, 255));
    Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    LogoEmpresa.setBackground(new java.awt.Color(255, 255, 255));
    LogoEmpresa.setForeground(new java.awt.Color(255, 255, 255));
    LogoEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images2/fondo.jpg"))); // NOI18N
    Fondo.add(LogoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 420));

    Header.setBackground(new java.awt.Color(51, 51, 51));
    Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
      public void mouseDragged(java.awt.event.MouseEvent evt) {
        HeaderMouseDragged(evt);
      }
    });
    Header.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        HeaderMousePressed(evt);
      }
    });

    ExitBtn.setBackground(new java.awt.Color(51, 51, 51));
    ExitBtn.setPreferredSize(new java.awt.Dimension(40, 40));
    ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        ExitBtnMouseClicked(evt);
      }
    });

    Exit.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
    Exit.setForeground(new java.awt.Color(255, 255, 255));
    Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    Exit.setText("X");
    Exit.setPreferredSize(new java.awt.Dimension(40, 40));

    javax.swing.GroupLayout ExitBtnLayout = new javax.swing.GroupLayout(ExitBtn);
    ExitBtn.setLayout(ExitBtnLayout);
    ExitBtnLayout.setHorizontalGroup(
      ExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ExitBtnLayout.createSequentialGroup()
        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    ExitBtnLayout.setVerticalGroup(
      ExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ExitBtnLayout.createSequentialGroup()
        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    NameInterfaz.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
    NameInterfaz.setForeground(new java.awt.Color(255, 255, 255));
    NameInterfaz.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    NameInterfaz.setText("LOGIN - Correo");
    NameInterfaz.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

    IconInterfaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images2/Logo.png"))); // NOI18N
    IconInterfaz.setMaximumSize(new java.awt.Dimension(40, 40));
    IconInterfaz.setPreferredSize(new java.awt.Dimension(40, 40));

    javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
    Header.setLayout(HeaderLayout);
    HeaderLayout.setHorizontalGroup(
      HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
        .addComponent(IconInterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(NameInterfaz)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 490, Short.MAX_VALUE)
        .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    HeaderLayout.setVerticalGroup(
      HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(ExitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(NameInterfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(HeaderLayout.createSequentialGroup()
        .addComponent(IconInterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    Fondo.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

    InfoCorreo.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
    InfoCorreo.setForeground(new java.awt.Color(51, 135, 253));
    InfoCorreo.setText("CORREO");
    Fondo.add(InfoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

    correoTxt.setBackground(new java.awt.Color(255, 255, 255));
    correoTxt.setForeground(new java.awt.Color(153, 153, 153));
    correoTxt.setActionCommand("<Not Set>");
    correoTxt.setBorder(null);
    correoTxt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        correoTxtActionPerformed(evt);
      }
    });
    Fondo.add(correoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 110, 30));

    InfoContra.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
    InfoContra.setForeground(new java.awt.Color(51, 135, 253));
    InfoContra.setText("CONTRASEÑA");
    Fondo.add(InfoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

    contraTxt.setBackground(new java.awt.Color(255, 255, 255));
    contraTxt.setText("Ingrese su correo");
    contraTxt.setBorder(null);
    Fondo.add(contraTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 140, 30));

    LoginBtn.setBackground(new java.awt.Color(204, 204, 0));

    LoginInfo.setForeground(new java.awt.Color(51, 51, 51));
    LoginInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    LoginInfo.setText("OK");

    javax.swing.GroupLayout LoginBtnLayout = new javax.swing.GroupLayout(LoginBtn);
    LoginBtn.setLayout(LoginBtnLayout);
    LoginBtnLayout.setHorizontalGroup(
      LoginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(LoginInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
    );
    LoginBtnLayout.setVerticalGroup(
      LoginBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(LoginInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
    );

    Fondo.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 100, 30));
    Fondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 110, 10));
    Fondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 140, 10));

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images2/FondoUser4.jpeg"))); // NOI18N
    Fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 460, 420));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
    xMouse = evt.getX();
    yMouse = evt.getY();
  }//GEN-LAST:event_HeaderMousePressed

  private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
    int x = evt.getXOnScreen();
    int y = evt.getYOnScreen();
    this.setLocation(x - xMouse, y - yMouse);
  }//GEN-LAST:event_HeaderMouseDragged

  private void ExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseClicked
    System.exit(0);
  }//GEN-LAST:event_ExitBtnMouseClicked

  private void correoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoTxtActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_correoTxtActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(LoginCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(LoginCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(LoginCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(LoginCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new LoginCorreo().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Exit;
  private javax.swing.JPanel ExitBtn;
  private javax.swing.JPanel Fondo;
  private javax.swing.JPanel Header;
  private javax.swing.JLabel IconInterfaz;
  private javax.swing.JLabel InfoContra;
  private javax.swing.JLabel InfoCorreo;
  private javax.swing.JPanel LoginBtn;
  private javax.swing.JLabel LoginInfo;
  private javax.swing.JLabel LogoEmpresa;
  private javax.swing.JLabel NameInterfaz;
  private javax.swing.JTextField contraTxt;
  private javax.swing.JTextField correoTxt;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  // End of variables declaration//GEN-END:variables
}
